### ISSUE TITLE
Citing Sources

### ISSUE THREAD

**Issue by adavis46** [adavis46/olemiss-writ101#5]
Questions: https://drive.google.com/open?id=1WOLalq2Oqxaios4IiAV442bRkh9oKSLPmR87O5oVn08

Content: https://drive.google.com/open?id=1oZikvtIqYcMKdWaxuUHCpfVfMGKMcX8tim4wgFRbvUY

**Comment by adavis46** [comment]
### APA vs. MLA
the original idea was to talk about style guides generally without focusing on one or the other. That is easier said than done, and students need specific examples. MLA may be harder to deal with bc of changes in recent editions (and inconsistent application by teachers). What if we just switch to APA?

**Comment by kforgett** [comment]
Hi Andrew,

I'm fine with that.

Best,

Karen


--

Karen Forgette (pronounced 4-jet)

Core Lecturer

Department of Writing and Rhetoric

B20 Lamar Hall, 3rd Floor

University of Mississippi

University, MS 38677

________________________________
